/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import clases.ListaTareas;
import clases.Indices;
import clases.Tarea;
import java.awt.Color;
import javax.swing.JOptionPane;


public class InterfazRegistro extends javax.swing.JFrame {

    /**
     * Creates new form InterfazRegistro
     */
    
    InterfazBuscar buscar;
    String usuario;
    ListaTareas c1;
    
    public InterfazRegistro(String u1) {
        initComponents();
        this.setLocationRelativeTo(null);
        usuario = u1;
        txtUsuario.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtUsuario.setText(u1);
        this.c1 = new ListaTareas();
    }

    private InterfazRegistro() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblBorrar = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        lblNew = new javax.swing.JLabel();
        btnBorrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        lblFondoA = new javax.swing.JLabel();
        txtInformacion = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblFecha = new javax.swing.JLabel();
        lblMateria = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        txtMateria = new javax.swing.JTextField();
        txtxFechaEnvio = new javax.swing.JTextField();
        lblFechaEnvio = new javax.swing.JLabel();
        txtFechaEntrega = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        btnIngresarMateria = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblEliminar = new javax.swing.JLabel();
        btnLimpiarLista = new javax.swing.JButton();
        txtDescripción = new javax.swing.JScrollPane();
        txtDescripcionTarea = new javax.swing.JTextArea();
        lblFondo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ver detalles");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Bienvenido: ");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ADMINISTRADOR DE");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 150, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("TAREAS");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        lblBorrar.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblBorrar.setForeground(new java.awt.Color(255, 255, 255));
        lblBorrar.setText("Eliminar tarea");
        getContentPane().add(lblBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 90, -1));

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 80, -1));

        lblNew.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblNew.setForeground(new java.awt.Color(255, 255, 255));
        lblNew.setText("Nueva tarea");
        getContentPane().add(lblNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 120, 30));

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icon delete.png"))); // NOI18N
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 60, 60));

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icon search.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 60, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Registro de información");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, 25));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Lista de Tareas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 100, 30));

        btnRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icon new.png"))); // NOI18N
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 60, 60));

        txtUsuario.setEditable(false);
        txtUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setBorder(null);
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 80, 20));

        lblFondoA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/7.jpg"))); // NOI18N
        lblFondoA.setText("Bienvenido: ");
        getContentPane().add(lblFondoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 470));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        txtInformacion.setViewportView(jTextArea1);

        getContentPane().add(txtInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 220, 390));

        lblFecha.setText("Fecha de entrega:");
        getContentPane().add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        lblMateria.setText("Nombre:");
        getContentPane().add(lblMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        lblHora.setText("Hora de entrega:");
        getContentPane().add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        lblDescripcion.setText("Descripción:");
        getContentPane().add(lblDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));
        getContentPane().add(txtMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 240, 30));
        getContentPane().add(txtxFechaEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 240, 30));

        lblFechaEnvio.setText("Fecha de envio:");
        getContentPane().add(lblFechaEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));
        getContentPane().add(txtFechaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 240, 30));
        getContentPane().add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 240, 30));

        btnIngresarMateria.setText("REGISTRAR TAREA");
        btnIngresarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarMateriaActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresarMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 160, 30));

        jLabel5.setText("Nombre de tarea a eliminar:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, -1, -1));

        lblEliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEliminar.setText("Eliminar tarea:");
        getContentPane().add(lblEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, -1, -1));

        btnLimpiarLista.setText("LIMPIAR LISTA");
        btnLimpiarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarListaActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiarLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, -1, -1));

        txtDescripcionTarea.setColumns(20);
        txtDescripcionTarea.setRows(5);
        txtDescripción.setViewportView(txtDescripcionTarea);

        getContentPane().add(txtDescripción, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 340, 110));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoRegistrar.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 810, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        btnSalir.setBackground(Color.red);
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        btnSalir.setBackground(Color.white);
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if(this.c1.estaVacia()){
            JOptionPane.showMessageDialog(null, "La lista está vacía. Ingrese tareas para continuar.", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            buscar = new InterfazBuscar(c1);
            buscar.setVisible(true); 
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        if(this.c1.estaVacia()){
            JOptionPane.showMessageDialog(null, "La lista está vacía. Ingrese tareas para continuar.", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            Tarea tareaBorrar = new Tarea(txtID.getText());
            Tarea tareaEncontrada = c1.obtener(tareaBorrar);
            if(tareaEncontrada != null) c1.eliminar(tareaEncontrada);
            else JOptionPane.showMessageDialog(null, "No se ha encontrado la tarea.", "Error de búsqueda", JOptionPane.ERROR_MESSAGE);
            this.jTextArea1.setText(c1.toString()); 
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        txtMateria.setText("");
        txtFechaEntrega.setText("");
        txtHora.setText("");
        txtxFechaEnvio.setText("");
        txtDescripcionTarea.setText("");
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnIngresarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarMateriaActionPerformed
        String nombre = txtMateria.getText();
        String descripcion = txtDescripcionTarea.getText();
        String fechaEnvio = txtxFechaEnvio.getText();
        String fechaEntrega = txtFechaEntrega.getText();
        String horaEntrega = txtHora.getText();
        Tarea tareaNew = new Tarea(nombre, descripcion, fechaEnvio, fechaEntrega, horaEntrega);
        c1.agregarFinal(tareaNew);
        this.jTextArea1.setText(c1.toString());
    }//GEN-LAST:event_btnIngresarMateriaActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        this.btnBorrarActionPerformed(evt);
    }//GEN-LAST:event_txtIDActionPerformed

    private void btnLimpiarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarListaActionPerformed
        if(!this.c1.estaVacia()){
            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Está seguro que quiere borrar toda la lista?\nEsta acción no se puede rehacer.", "Confirmación", JOptionPane.YES_NO_OPTION);
            if(confirmacion == JOptionPane.YES_OPTION) this.c1.limpiar();
            this.jTextArea1.setText(c1.toString());
        }
    }//GEN-LAST:event_btnLimpiarListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnIngresarMateria;
    private javax.swing.JButton btnLimpiarLista;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblBorrar;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaEnvio;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblFondoA;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblMateria;
    private javax.swing.JLabel lblNew;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextArea txtDescripcionTarea;
    private javax.swing.JScrollPane txtDescripción;
    private javax.swing.JTextField txtFechaEntrega;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtID;
    private javax.swing.JScrollPane txtInformacion;
    private javax.swing.JTextField txtMateria;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtxFechaEnvio;
    // End of variables declaration//GEN-END:variables
}
